---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shorewall
data:
  policy: |
    #SOURCE		DEST		POLICY	LOGLEVEL	LIMIT

    # fw gets everywhere for now
    $FW       all     ACCEPT

    # Zones with internet access
    oldloc    net     ACCEPT
    loc       net     ACCEPT
    guest     net     ACCEPT

    # Default reject with log
    all       all     REJECT  info

  rules: |
    #ACTION	    	SOURCE		DEST		PROTO	DPORT	SPORT   ORIGDEST
    Ping(ACCEPT)  all       $FW

    SSH(ACCEPT)   oldloc    $FW

    DNS(ACCEPT)   oldloc    $FW
    DNS(ACCEPT)   loc       $FW
    DNS(ACCEPT)   mgmt      $FW
    DNS(ACCEPT)   guest     $FW
    DNS(ACCEPT)   k8s       oldloc

    mDNS(ACCEPT)	oldloc	 	$FW
    mDNS(ACCEPT)	loc	    	$FW

    # K8S
    ACCEPT        oldloc    $FW     TCP   6443 # api server

  interfaces: |
    ?FORMAT 2
    #ZONE	  INTERFACE	OPTIONS
    net     enp4s0    dhcp
    oldloc  enp2s0    dhcp
    mgmt    mgmt      dhcp
    loc     loc       dhcp
    guest   guest     dhcp

    k8s     cni0      routeback

  zones: |
    #ZONE   TYPE             OPTIONS
    fw      firewall
    net     ip
    oldloc  ip
    mgmt    ip
    loc     ip
    guest   ip
    k8s     ip

  snat: |
    # ACTION        SOURCE              DEST
    MASQUERADE      enp2s0              enp4s0
    MASQUERADE      mgmt                enp4s0
    MASQUERADE      loc                 enp4s0
    MASQUERADE      guest               enp4s0
    MASQUERADE      cni0                enp4s0
