---
namespace: default
helmCharts:
- name: coredns
  releaseName: main
  version: 1.16.4
  repo: https://coredns.github.io/helm
  valuesInline:
    rbac:
      create: false

    isClusterService: false

    serviceType: LoadBalancer

    servers:
    - port: 53
      zones:
      - zone: .
        scheme: dns://
      plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
