apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  labels:
    app: dnsmasq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      hostNetwork: true
      containers:
        - name: dnsmasq
          image: 4km3/dnsmasq:2.86-r0
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - name: dns
              containerPort: 53
            - name: dhcp
              containerPort: 67
